### PR TITLE
update schema to fix errors with clickhouse 23.9

### PR DESCRIPTION
**Pull request by gusinacio**
https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#improvement

Clickhouse on version 23.9 updated `information_schema.tables.table_type`  from Enum8 to String

### CODE REVIEW

**Review by maoueh — APPROVED** [review]

**Comment by maoueh** [comment]
Do I get right now that version `23.9` will be required now as the minimum version?

**Comment by gusinacio** [comment]
No, it will be backward compatible. Enum8 can be compared against Integers and Strings, while Strings can only be compared against Strings.

I updated the query to use string in the WHERE clause, it should work with the older versions and the newer one.

**Comment by maoueh** [comment]
> I updated the query to use string in the WHERE clause, it should work with the older versions and the newer one.

In your own code? Because I don't see such change in the PR. Actually my question is, am I good to merge the PR now?

**Comment by sduchesneau** [comment]
Tested it on 23.3, it breaks compatibility. Let's try to honor the 1-year support period of the LTS (up to 2024-03)

```2023-11-27T10:17:16.679-0500 ERRO (sink-sql) new db loader: load psql table: retrieving table and schema: code: 53, message: Cannot convert string BASE TABLE to type UInt8: while executing 'FUNCTION equals(multiIf(is_temporary, 4, like(engine, '%View'), 2, like(engine, 'System%'), 5, equals(has_own_data, 0), 3, 1) : 19, 'BASE TABLE' : 14) -> equals(multiIf(is_temporary, 4, like(engine, '%View'), 2, like(engine, 'System%'), 5, equals(has_own_data, 0), 3, 1), 'BASE TABLE') UInt8 : 20'```

**Pull request closed without merging**
