### PR TITLE
feat: wip rollback sinker

### PR DESCRIPTION
**Pull request by pedrotambo**

### CODE REVIEW

**Comment by maoueh** [comment]
Can you describe a bit the rollback server piece? Is this a Postgres feature or an external "custom" server?

**Comment by pedrotambo** [comment]
Ups! Just wanted to create a PR for my fork, sorry :sweat_smile:

**Comment by maoueh** [comment]
Still interested to know the answer if you are ok to share :D

**Comment by pedrotambo** [comment]
Yeah of course. As you said, it is an external custom server that does the rollback stuff for that specific database model

**Comment by maoueh** [comment]
And this custom server, it rollback using something like `DELETE FROM T WHERE block_num <= X` is that is or do you have another logic implemented?

Because if I recall right, your use case is "append only" style of operation right (e.g. you have only CREATE operations)?

**Comment by pedrotambo** [comment]
Well, yes, partly. That is the use case of my team work Juanma. But I'm indexing another set of tables where I need a field of one table to be updated. So before the `DELETE` statements I'm implementing some logic to revert the state of that field (that information is stored in another insert-only table).

**Comment by maoueh** [comment]
Ok thank you for the extra details. Definitely something that is generic and which could be included if you want at some point in time. 

I think we should probably support multiple undos strategies as there is tradeoff for any undo strategy used.

**Comment by pedrotambo** [comment]
Yes, that makes sense. That would be nice.

Happy to share.

**Pull request closed without merging**
